[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ipyslides"
dynamic = ["version"]
description = "Live rich content slides in jupyter notebook"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
license = "MIT"
authors = [
  { name = "Abdul Saboor", email = "asaboor.my@outlook.com" },
]
keywords = ["Jupyter", "Widgets", "IPython"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dependencies = [
  "markdown",
  "ipywidgets>=8.0.4",
  "pillow>=9.3.0",
  "anywidget==0.9.13",
  "tldraw==2.2.4",
  "dashlab",
  "pyyaml",
]

[project.optional-dependencies]
extra = [
  "jupyterlab>=3.5.2",
  "ipython>=9.0",
]

[project.urls]
Homepage = "https://github.com/asaboor-gh/ipyslides"
"Bug Tracker" = "https://github.com/asaboor-gh/ipyslides/issues"

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = {attr = "ipyslides.__version__.__version__"}

[tool.setuptools.packages.find]
exclude = ["tests", "*.tests", "*.tests.*", "tests.*"]

[tool.setuptools.package-data]
ipyslides = [
  "pkg_nbs/*.ipynb",
  "_base/static/*.js",
  "_base/static/*.css",
]
